### ISSUE TITLE
Missing ViT_ti_GD_SD_classification weights

### ISSUE THREAD

**Issue by terry-for-github** [pengzhiliang/G2SD#6]
Thanks for releasing the model weights! But there is no checkpoint.pth file when I opened the "ViT_ti_GD_SD_classification" folder at the google drive link. Was this file somehow missing? Would you please upload that vit_tiny weights again? I'll really appreciate it!

**Comment by Vickeyhw** [comment]
@terry-for-github Sorry for missing the checkpoint file of ViT_ti_GD_SD_classification.  The original file was accidentally deleted. If you have GPU resources, you can try to finetune with distillation from the "ViT_Ti_GD.pth".  Since I don't have available GPUs recently, maybe I'll rerun this experiment later and upload that vit_tiny weights again.

**Comment by terry-for-github** [comment]
Thanks for your friendly reply! I'll consider fine-tuning myself.
